### ISSUE TITLE
Implement scroll view in relevant xml files

### ISSUE THREAD

**Issue by anantcodes** [anantcodes/Coding-Guide#1]

**Comment by amindadgar** [comment]
Done in #3 in the second commit !

**Comment by peculiaruc** [comment]
Please I will like to work on this, can I take it up?

I will pull the project, look for the XML files where the scroll view is applicable and add it without breaking the app

**Comment by peculiaruc** [comment]
please has this be taken, I am interested in it

**Comment by anantcodes** [comment]
@peculiaruc you can definitely work on this .

**Comment by peculiaruc** [comment]
Thanks

**Comment by peculiaruc** [comment]
Done
i have send a PR
