### ISSUE TITLE
Update the readme for Competitive programming 

### ISSUE THREAD

**Issue by anantcodes** [anantcodes/Coding-Guide#6]
In the readme.md file , put a heading of Competitive programming and write all the features you encounter under this domain.

**Comment by ghost** [comment]
Sir, I would like to contribute to this. Please assign it to me.

**Comment by anantcodes** [comment]
Yeah sure

**Comment by anantcodes** [comment]
Good work 
Thanks for your contribution.

**Comment by ghost** [comment]
Thankyou for letting me do so!
